name: Deployment

on:
  push:
    branches: [master]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm install hexo-cli -g 
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: phantooom
        GIT_EMAIL: xiaorui.zou@gmail.com
      run: |
        git config --global init.defaultBranch master
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        cd public && git init && git add .
        git commit -m "Site deployed by GitHub Actions"
        git remote add blog https://${{ secrets.GITHUB_TOKEN }}@github.com/phantooom/phantooom.github.io.git
        git push --force --quiet blog master
